import React, { useRef } from 'react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { Download, FileText, CheckCircle, FileJson } from 'lucide-react';

export default function DocumentPreview({ data }) {
  const printRef = useRef();

  const handleDownloadPdf = async () => {
    const element = printRef.current;
    if (!element) return;

    try {
      const canvas = await html2canvas(element, { scale: 2, useCORS: true });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
      
      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      pdf.save(`${data.projectName.replace(/\s+/g, '_')}_PRD.pdf`);
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Failed to generate PDF. Check console for details.');
    }
  };

  const handleDownloadMarkdown = () => {
    const { projectName, version, status, vision, problemStatement, targetAudience, userStories, features, techStack } = data;
    const date = new Date().toLocaleDateString();

    const mdContent = `# Product Requirements Document: ${projectName}
    
**Version:** ${version}  
**Status:** ${status}  
**Date:** ${date}

---

## 1. Product Vision
${vision || 'N/A'}

### Problem Statement
${problemStatement || 'N/A'}

---

## 2. Target Audience & Users
### User Personas
${targetAudience.length > 0 ? targetAudience.map(p => `- ${p}`).join('\n') : '_No personas defined._'}

### Key User Stories
${userStories.length > 0 ? userStories.map(s => `- ${s}`).join('\n') : '_No user stories defined._'}

---

## 3. Functional Requirements
${features.length > 0 ? features.map((f, i) => `### 3.${i + 1} ${f.title}
${f.description}`).join('\n\n') : '_No features defined._'}

---

## 4. Technical Architecture
- **Frontend:** ${techStack.frontend || 'N/A'}
- **Backend:** ${techStack.backend || 'N/A'}
- **Database:** ${techStack.database || 'N/A'}
- **Infrastructure:** ${techStack.infrastructure || 'N/A'}

---

_Generated by PRD Generator_
`;

    const blob = new Blob([mdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${projectName.replace(/\s+/g, '_')}_PRD.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const Section = ({ title, children, className = "" }) => (
    <div className={`mb-8 ${className}`}>
      <h2 className="text-xl font-bold text-gray-800 border-b-2 border-indigo-100 pb-2 mb-4">{title}</h2>
      {children}
    </div>
  );

  return (
    <div className="h-full flex flex-col items-center">
      
      <div className="w-full flex justify-between items-center mb-6">
        <div>
           <h2 className="text-2xl font-bold text-white">Review & Export</h2>
           <p className="text-white/50 text-sm">Review your document before exporting.</p>
        </div>
        <div className="flex gap-3">
          <button 
            onClick={handleDownloadMarkdown}
            className="glass-button px-6 py-2.5 rounded-lg font-bold flex items-center gap-2 hover:bg-white/10"
          >
            <FileText size={18} /> Export Markdown
          </button>
          <button 
            onClick={handleDownloadPdf}
            className="bg-gradient-to-r from-indigo-500 to-purple-500 hover:from-indigo-600 hover:to-purple-600 text-white px-6 py-2.5 rounded-lg font-bold shadow-lg shadow-indigo-500/25 flex items-center gap-2 transform hover:scale-105 transition-all"
          >
            <Download size={18} /> Download PDF
          </button>
        </div>
      </div>

      {/* Document Viewport - A4 Ratio - Light Mode for better printing */}
      <div className="flex-1 w-full overflow-auto bg-gray-900/50 p-4 rounded-xl border border-white/5">
        <div 
          ref={printRef}
          className="bg-white text-gray-900 w-full max-w-[210mm] min-h-[297mm] mx-auto p-[20mm] shadow-2xl origin-top"
        >
          {/* Header */}
          <div className="text-center mb-12 border-b-4 border-indigo-600 pb-6">
            <h1 className="text-4xl font-extrabold text-gray-900 mb-2">{data.projectName || 'Untitled Project'}</h1>
            <p className="text-xl text-indigo-600 font-medium tracking-wide">Product Requirements Document</p>
            <div className="flex justify-center gap-6 mt-4 text-sm text-gray-500">
              <span>Version: {data.version}</span>
              <span>Status: {data.status}</span>
              <span>Date: {new Date().toLocaleDateString()}</span>
            </div>
          </div>

          {/* 1. Vision */}
          <Section title="1. Product Vision">
            <div className="bg-indigo-50 p-4 rounded-lg border-l-4 border-indigo-500 mb-4">
              <h3 className="font-bold text-indigo-900 mb-1">Vision Statement</h3>
              <p className="text-gray-700 leading-relaxed">{data.vision || 'N/A'}</p>
            </div>
            {data.problemStatement && (
               <div className="mt-4">
                <h3 className="font-bold text-gray-900 mb-1">Problem Statement</h3>
                <p className="text-gray-700 leading-relaxed">{data.problemStatement}</p>
               </div>
            )}
          </Section>

          {/* 2. Target Audience */}
          <Section title="2. Target Audience & Users">
            <h3 className="font-bold text-gray-900 mb-2">User Personas</h3>
            <ul className="list-disc list-inside mb-4 text-gray-700">
              {data.targetAudience.length > 0 ? (
                data.targetAudience.map((persona, i) => <li key={i}>{persona}</li>)
              ) : ( <li className="text-gray-400 italic">No personas defined.</li> )}
            </ul>
            
            <h3 className="font-bold text-gray-900 mb-2">Key User Stories</h3>
            <div className="space-y-2">
              {data.userStories.length > 0 ? (
                data.userStories.map((story, i) => (
                  <div key={i} className="flex gap-2 items-start">
                    <span className="text-indigo-500 font-bold">•</span>
                    <p className="text-gray-700">{story}</p>
                  </div>
                ))
              ) : ( <p className="text-gray-400 italic">No user stories defined.</p> )}
            </div>
          </Section>

           {/* 3. Features */}
           <Section title="3. Functional Requirements">
             <div className="grid gap-4">
              {data.features.length > 0 ? (
                data.features.map((feature, i) => (
                  <div key={i} className="border border-gray-200 rounded-lg p-4 bg-gray-50 break-inside-avoid">
                    <h4 className="font-bold text-lg text-gray-800 mb-2">{i + 1}. {feature.title}</h4>
                    <p className="text-gray-700 whitespace-pre-line">{feature.description}</p>
                  </div>
                ))
              ) : ( <p className="text-gray-400 italic">No features defined.</p> )}
             </div>
           </Section>

           {/* 4. Tech Stack */}
           <Section title="4. Technical Architecture">
             <div className="grid grid-cols-2 gap-6">
                <div>
                  <h4 className="font-bold text-gray-700 text-sm uppercase tracking-wider mb-2">Frontend</h4>
                  <p className="text-gray-800 bg-gray-100 p-3 rounded">{data.techStack.frontend || 'N/A'}</p>
                </div>
                <div>
                  <h4 className="font-bold text-gray-700 text-sm uppercase tracking-wider mb-2">Backend</h4>
                  <p className="text-gray-800 bg-gray-100 p-3 rounded">{data.techStack.backend || 'N/A'}</p>
                </div>
                <div>
                  <h4 className="font-bold text-gray-700 text-sm uppercase tracking-wider mb-2">Database</h4>
                  <p className="text-gray-800 bg-gray-100 p-3 rounded">{data.techStack.database || 'N/A'}</p>
                </div>
                <div>
                  <h4 className="font-bold text-gray-700 text-sm uppercase tracking-wider mb-2">Infrastructure</h4>
                  <p className="text-gray-800 bg-gray-100 p-3 rounded">{data.techStack.infrastructure || 'N/A'}</p>
                </div>
             </div>
           </Section>

        </div>
      </div>
    </div>
  );
}
